
export default
{
     //commonPlaceHolders
     commonPlaceHolder:'Enter your',

     //common symbols
     gap:' ',
     dollar:'$',
    //Authentication Strings
    sign:'Sign',
    up:'up',
    in:'in',
    email:'Email',
    items:'items',
    name:'Name',
    password:'Password',
    alreadyHaveAnAccount:'Already have an account?',
    login:'Login',
    or:'Or',
    withSocialAccout:'with social account',
    forgetPassword:'Forget Password?',
    //shoppageStrings
    categories:'Categories',
    summerSale:'SUMMER SALES',
    offText:'Up to 50% off',
    filters:'Filters',
    priceRange:'Price range',
    ratingRange:'Rating range',
    brands:'Brands',
    search:'Search',
    discard:'Discard',
    apply:'Apply',
    sortBy:'Sort By',
    addToCart:'ADD TO CART',
    shippingInfo:'Shipping info',
    additionalInformation:'Additional Information',
    rating:'Rating',
    addReview:'Add Review',
    RatingsAndRevies:'Ratings And Reviews',
    writeAReview:'Write a review',
    whatIsYourRate:'What is you rate?',
    pleaseShareYourOpinion:'Please share your opinion about the product',
    yourReview:'Your Review',
    sendReview:'SEND REVIEW',
    updateReview:'UPDATE REVIEW',
    alreadyInBag:'Already in Bag',
    youCanAlsoLikeThis:'You can also like this',
    myBag:'My Bag',
    totalAmount:'Total Amount',
    checkOut:'CHECK OUT',
    //home
    fasionSale:'Fashion Sale',
    check:'Check',
    new:'New',
    sale:'Sale',
    youNeverSeenItBefore:'You\'ve never seen it before',
    viewAll:'View all',
    streetClothes:'Street Clothes',
    superSummerSale:'Super Summer Sale',
    Favorites:'Favorites',
    //harsh ui
    aboutWanderobe:'About Wanderobe',
    travelLightexplor:'Travel light.   Explore deeply. Dress',
    meaningfully:' meaningfully.' ,
    longText:'At WANDEROBE, we believe fashion is a journey that connects you to the places you explore. Our hospitality fashion service delivers exclusive, locally inspired apparel from emerging designers directly to your hotel. Browse our curated collection before your trip, try on unique pieces during your stay, and immerse yourself in the destination’s style. When it’s time to move on, we’ll handle the logistics—no stress, just effortless fashion.',
    //profile
    myProfile:'My profile',
    myOrders:'My orders',
    alreadyHave:'Already have',
    orders:'orders',
    order:'order',
    noOrdersYet:'No orders Yet',
    myReview:'My Reviews',
    noReviwsYet:'No reviwes Yet',
    review:'Reviews',
    for:'for',
    orderNo:'Order No :-',
    qunatity:'Quantity :- ',
    details:'Details',
    orderDetails:'Order Details',
    brand:'brand :',
    tags:'tags :',
    units:'Units :',
    settings:'Settings',
    notifications:'Notifications',
    personalInformation:'Personal Information',
    changePassword:'Change Password',
    personal:'Personal',
    editPersonalInformation:'Edit Personal Information',
    saveChanges:'Save Changes',
    logOut:'Log Out',
    cancel:'Cancel',
    Home:'Home',
    shop:'Shop',
    bag:'Bag',
    profile:'Profile',
    favorite:'Favorite',




};
